---
- name: Remove any existing Puppet release packages for versions other than {{ foreman_puppet_repositories_version }}
  package:
    name: "puppet{{ item }}-release"
    state: absent
  loop: "{{ foreman_puppet_repositories_supported_versions | difference([foreman_puppet_repositories_version | string]) }}"

- name: 'Include {{ ansible_os_family }}'
  include_tasks: '{{ ansible_os_family | lower }}.yml'
