---
- name: Ensure running on EL8
  ansible.builtin.assert:
    that:
      - ansible_os_family == "RedHat"
      - ansible_distribution_major_version == '8'
    fail_msg: "This role is only supported on EL8"

- name: Get version from the PostgreSQL data directory
  ansible.builtin.slurp:
    path: /var/lib/pgsql/data/PG_VERSION
  register: pg_version

- name: Perform PostgreSQL upgrade
  when:
    - "'10' in pg_version['content']|b64decode"
  block:
    - name: Start postgresql
      ansible.builtin.service:
        name: postgresql
        state: started

    - name: Collect postgres data
      ansible.builtin.shell: psql --list --tuples-only | grep -E "^\s+postgres"
      become: true
      become_user: postgres
      changed_when: false
      register: postgres_output

    - name: Set collate and ctype facts
      ansible.builtin.set_fact:
        collate: "{{ postgres_output.stdout.split('|')[3] | trim }}"
        ctype: "{{ postgres_output.stdout.split('|')[4] | trim }}"

    - name: Stop postgresql
      ansible.builtin.service:
        name: postgresql
        state: stopped

    # https://bugzilla.redhat.com/show_bug.cgi?id=1935301
    - name: Update postgresq.conf data directory
      ansible.builtin.lineinfile:
        path: /var/lib/pgsql/data/postgresql.conf
        regexp: '^data_directory ='
        line: ''

    - name: Enable postgresql:12 module
      ansible.builtin.dnf:
        name: '@postgresql:12'
        state: present

    - name: Update postgresql packages  # noqa package-latest
      ansible.builtin.dnf:
        name:
          - postgresql-server
          - postgresql-upgrade
        state: latest

    - name: Run postgresql-setup --upgrade  # noqa no-changed-when
      ansible.builtin.command: postgresql-setup --upgrade
      environment:
        PGSETUP_INITDB_OPTIONS: "--lc-collate={{ collate }} --lc-ctype={{ ctype }} --locale={{ collate }}"

    - name: Start postgresql
      ansible.builtin.service:
        name: postgresql
        state: started
